# Example config
version: "development branch"

monitor:
  period: 3
  algorithm: "sha256"
  log:
    silent: false
    secure: true
    verbosity: 3

files:
  - "index.html"

filter:
  - file: "index.html"
    lines: "8,2-4"
